-- MySQL Script generated by MySQL Workbench
-- Thu Dec 13 03:08:20 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema loja
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema loja
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `loja` ;
USE loja;

-- -----------------------------------------------------
-- Table `loja`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS cliente (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(150) NOT NULL,
  `sexo` VARCHAR(9) NOT NULL,
  `nascimento` DATE NOT NULL,
  `cpf` INT NOT NULL,
  `cartao` INT NOT NULL,
  `codcartao` INT NOT NULL,
  `vencimentocartao` DATE NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `senha` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS tipo (
  `id` INT NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS produto (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(70) NOT NULL,
  `descricao` VARCHAR(300) NOT NULL,
  `tamanho` VARCHAR(4) NOT NULL,
  `cor` VARCHAR(15) NOT NULL,
  `foto` VARCHAR(150) NULL,
  `quantidade` INT NOT NULL,
  `tipo_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tipo_id`),
  INDEX `fk_produto_tipo1_idx` (`tipo_id` ASC) VISIBLE,
  CONSTRAINT `fk_produto_tipo1`
    FOREIGN KEY (`tipo_id`)
    REFERENCES tipo(`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS compra (
  `cliente_id` INT NOT NULL,
  `produto_id` INT NOT NULL,
  `produto_tipo_id` INT NOT NULL,
  `data` DATE NULL,
  `quantidade` INT NULL,
  PRIMARY KEY (`cliente_id`, `produto_id`, `produto_tipo_id`),
  INDEX `fk_cliente_has_produto_produto1_idx` (`produto_id` ASC, `produto_tipo_id` ASC) VISIBLE,
  INDEX `fk_cliente_has_produto_cliente1_idx` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_has_produto_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES cliente (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_produto_produto1`
    FOREIGN KEY (`produto_id` , `produto_tipo_id`)
    REFERENCES produto (`id` , `tipo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
