-- MySQL Script generated by MySQL Workbench
-- Thu Dec 13 03:08:20 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema loja
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema loja
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `loja` ;
USE `loja` ;

-- -----------------------------------------------------
-- Table `loja`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loja`.`cliente`;
CREATE TABLE IF NOT EXISTS `loja`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(150) NOT NULL,
  `sexo` VARCHAR(9) NOT NULL,
  `nascimento` DATE NOT NULL,
  `endereco` VARCHAR(200) NOT NULL,
  `cidade` VARCHAR(80) NOT NULL,
  `estado` VARCHAR(80) NOT NULL,
  `pais` VARCHAR(80) NOT NULL,
  `cep` INT NOT NULL,
  `cpf` INT NOT NULL,
  `cartao` INT NOT NULL,
  `codcartao` INT NOT NULL,
  `vencimentocartao` DATE NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `senha` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja`.`tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loja`.`tipo`;
CREATE TABLE IF NOT EXISTS `loja`.`tipo` (
  `id` INT NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja`.`produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loja`.`produto`;
CREATE TABLE IF NOT EXISTS `loja`.`produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(70) NOT NULL,
  `descricao` VARCHAR(300) NOT NULL,
  `tamanho` VARCHAR(4) NOT NULL,
  `cor` VARCHAR(15) NOT NULL,
  `foto` VARCHAR(150) NULL,
  `quantidade` INT NOT NULL,
  `idtipo` INT NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`idtipo`)
  REFERENCES `loja`.`tipo` (`id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `loja`.`compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loja`.`compra`;
CREATE TABLE IF NOT EXISTS `loja`.`compra` (
  `cliente_id` INT NOT NULL,
  `produto_id` INT NOT NULL,
  `produto_idtipo` INT NOT NULL,
  `data` DATE NULL,
  `quantidade` INT NULL,
  PRIMARY KEY (`cliente_id`, `produto_id`, `produto_idtipo`),
  FOREIGN KEY (`cliente_id`)
  REFERENCES `loja`.`cliente` (`id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
  FOREIGN KEY (`produto_id` , `produto_idtipo`)
  REFERENCES `loja`.`produto` (`id` , `idtipo`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
